import { PROJECT_STATUS, type ProjectItemProps } from '@/components/ProjectItem/projectStatus';

export const PROJECTS: ProjectItemProps[] = [
  {
    status: PROJECT_STATUS.ACTIVE,
    title: 'Personal Portfolio v2',
    description: 'Second iteration of my personal portfolio website.',
    year: 2025,
    featured: false,
    tags: ['TypeScript', 'React', 'Vite', 'Tailwind CSS'],
    githubUrl: 'https://github.com/jmurrah/personal-portfolio-v2',
    liveUrl: 'https://murrah.dev',
  },
  {
    status: PROJECT_STATUS.ACTIVE,
    title: 'LeetCode Repetition',
    description: 'Web extension enabling spaced repetition of LeetCode problems.',
    year: 2025,
    featured: true,
    tags: ['Go', 'TypeScript', 'Tailwind CSS', 'Supabase', 'AWS', 'OAuth2'],
    githubUrl: 'https://github.com/leetcode-repetition',
    liveUrl: 'https://leetcode-repetition.murrah.dev/',
  },
  {
    status: PROJECT_STATUS.PASSIVE,
    title: 'Online Tools',
    description: 'Directory of online tools I have made.',
    year: 2025,
    featured: false,
    tags: ['TypeScript', 'React', 'Vite', 'Tailwind CSS'],
    githubUrl: 'https://github.com/jmurrah/tools',
    liveUrl: 'https://tools.murrah.dev/',
  },
  {
    status: PROJECT_STATUS.SHUTDOWN,
    title: 'Personal Portfolio v1',
    description: 'First attempt at a personal portfolio website.',
    year: 2024,
    featured: false,
    tags: ['JavaScript', 'Tailwind CSS'],
    githubUrl: 'https://github.com/jmurrah/personal-portfolio-v1',
    liveUrl: 'https://v1.murrah.dev/',
  },
  {
    status: PROJECT_STATUS.SHUTDOWN,
    title: 'Commit Canvas',
    description: 'Create pixel art with your empty git commit history.',
    year: 2024,
    featured: false,
    tags: ['Python'],
    githubUrl: 'https://github.com/jmurrah/commit-canvas',
  },
  {
    status: PROJECT_STATUS.SHUTDOWN,
    title: 'Discord Bouncer',
    description: 'Discord bot that leverages Stripe payments for role assignment.',
    year: 2024,
    featured: false,
    tags: ['Python', 'Docker', 'Google Cloud', 'Stripe'],
    githubUrl: 'https://github.com/jmurrah/discord-bouncer',
  },
  {
    status: PROJECT_STATUS.PASSIVE,
    title: 'Pict Online',
    description: 'Browser-based UI for the Microsoft PICT tool.',
    year: 2025,
    featured: false,
    tags: ['TypeScript', 'React', 'Vite', 'Tailwind CSS'],
    githubUrl: 'https://github.com/jmurrah/pict-online',
    liveUrl: 'https://pict-online.murrah.dev/',
  },
  {
    status: PROJECT_STATUS.SHUTDOWN,
    title: 'Azimuth Calculator',
    description: 'Calculate the daily solar azimuth data for a period of time.',
    year: 2024,
    featured: false,
    tags: ['Python', 'CSV'],
    githubUrl: 'https://github.com/jmurrah/azimuth-calculator',
  },
];
