export const technologies = [
  { name: 'Python', accent: 'var(--tech-python)' },
  { name: 'TypeScript', accent: 'var(--tech-typescript)' },
  { name: 'React', accent: 'var(--tech-react)' },
  { name: 'Java', accent: 'var(--tech-java)' },
  { name: 'Go', accent: 'var(--tech-go)' },
  { name: 'AWS', accent: 'var(--tech-aws)' },
  { name: 'Google Cloud', accent: 'var(--tech-google-cloud)' },
  { name: 'Postman', accent: 'var(--tech-postman)' },
  { name: 'Supabase', accent: 'var(--tech-supabase)' },
  { name: 'MongoDB', accent: 'var(--tech-mongodb)' },
  { name: 'git', accent: 'var(--tech-git)' },
  { name: 'Docker', accent: 'var(--tech-docker)' },
  { name: 'Tailwind CSS', accent: 'var(--tech-tailwind)' },
  { name: 'Spring Boot', accent: 'var(--tech-spring)' },
  { name: 'FastAPI', accent: 'var(--tech-fastapi)' },
];
